version: '3'
networks:
  todos-network:
volumes:
  mongodbdata:
services:
  database:
    image: mongo:5.0.7
    volumes:
      - mongodbdata:/data/db
    networks:
      - todos-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadminpassword
  api:
    build: ./Api/src
    networks:
      - todos-network
    environment:
      - MongoDbSettings:Host=database
      - MongoDbSettings:Password=mongoadminpassword
  web:
    build: ./Web/src
    volumes:
      - ./Web/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:8080
    networks:
      - todos-network
