---
name: Build and Push Images to Google Cloud Platform
on:
  push:
    branches: [master]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: taschenka
      TASCHENKA_API: taschenka_api
      TASCHENKA_WEB: taschenka_web
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Build Docker Images
        run: |-
          docker build -t $TASCHENKA_API:latest ./Api/src
          docker build -t $TASCHENKA_WEB:latest ./Api/src

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

      - name: Push Docker Images to Container Registry
        env:
          GIT_TAG: v1.2.1
        run: |-
          docker tag $TASCHENKA_API:latest eu.gcr.io/$PROJECT_ID/$TASCHENKA_API:latest
          docker tag $TASCHENKA_API:latest eu.gcr.io/$PROJECT_ID/$TASCHENKA_API:$GIT_TAG
          docker push eu.gcr.io/$PROJECT_ID/$TASCHENKA_API:latest
          docker push eu.gcr.io/$PROJECT_ID/$TASCHENKA_API:$GIT_TAG
          docker tag $TASCHENKA_WEB:latest eu.gcr.io/$PROJECT_ID/$TASCHENKA_WEB:latest
          docker tag $TASCHENKA_WEB:latest eu.gcr.io/$PROJECT_ID/$TASCHENKA_WEB:$GIT_TAG
          docker push eu.gcr.io/$PROJECT_ID/$TASCHENKA_WEB:latest
          docker push eu.gcr.io/$PROJECT_ID/$TASCHENKA_WEB:$GIT_TAG

      - name: Push Docker Images to Artifact Registry
        env:
          GIT_TAG: v1.2.1
        run: |-
          docker tag $TASCHENKA_API:latest europe-central2-docker.pkg.dev/$PROJECT_ID/$TASCHENKA_API:latest
          docker tag $TASCHENKA_API:latest europe-central2-docker.pkg.dev/$PROJECT_ID/$TASCHENKA_API:$GIT_TAG
          docker push europe-central2-docker.pkg.dev/$PROJECT_ID/$TASCHENKA_API:latest
          docker push europe-central2-docker.pkg.dev/$PROJECT_ID/$TASCHENKA_API:$GIT_TAG
          docker tag $TASCHENKA_WEB:latest europe-central2-docker.pkg.dev/$PROJECT_ID/$TASCHENKA_WEB:latest
          docker tag $TASCHENKA_WEB:latest europe-central2-docker.pkg.dev/$PROJECT_ID/$TASCHENKA_WEB:$GIT_TAG
          docker push europe-central2-docker.pkg.dev/$PROJECT_ID/$TASCHENKA_WEB:latest
          docker push europe-central2-docker.pkg.dev/$PROJECT_ID/$TASCHENKA_WEB:$GIT_TAG
